// ============================================================
// ArogyaSutra — Main CDK Stack
// Provisions all AWS resources for the PHR platform:
//   KMS, Cognito, S3, DynamoDB, SNS, HealthLake, IAM
// ============================================================

import * as cdk from "aws-cdk-lib";
import * as kms from "aws-cdk-lib/aws-kms";
import * as cognito from "aws-cdk-lib/aws-cognito";
import * as s3 from "aws-cdk-lib/aws-s3";
import * as dynamodb from "aws-cdk-lib/aws-dynamodb";
import * as sns from "aws-cdk-lib/aws-sns";
import * as lambda from "aws-cdk-lib/aws-lambda";
import { NodejsFunction } from "aws-cdk-lib/aws-lambda-nodejs";
import * as iam from "aws-cdk-lib/aws-iam";
// NOTE: HealthLake is NOT available in ap-south-1.
// Create it manually in us-east-1 via the AWS Console.
import { Construct } from "constructs";
import * as path from "path";

export class ArogyaSutraStack extends cdk.Stack {
    constructor(scope: Construct, id: string, props?: cdk.StackProps) {
        super(scope, id, props);

        // ====================================================
        // 1. KMS — Customer Managed Key
        // ====================================================
        const masterKey = new kms.Key(this, "MasterKey", {
            alias: "arogyasutra-master-key",
            description: "ArogyaSutra root encryption key for envelope encryption",
            enableKeyRotation: true,
            removalPolicy: cdk.RemovalPolicy.RETAIN,
            pendingWindow: cdk.Duration.days(30),
        });

        // ====================================================
        // 2. S3 — Encrypted Health Records Bucket
        // ====================================================
        const healthBucket = new s3.Bucket(this, "HealthRecordsBucket", {
            // Bucket name auto-generated by CDK to avoid conflicts
            encryption: s3.BucketEncryption.KMS,
            encryptionKey: masterKey,
            blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
            versioned: true,
            enforceSSL: true,
            removalPolicy: cdk.RemovalPolicy.RETAIN,
            cors: [
                {
                    allowedOrigins: ["http://localhost:3000", "https://*.amplifyapp.com"],
                    allowedMethods: [
                        s3.HttpMethods.GET,
                        s3.HttpMethods.PUT,
                        s3.HttpMethods.POST,
                    ],
                    allowedHeaders: ["*"],
                    maxAge: 3600,
                },
            ],
            lifecycleRules: [
                {
                    id: "move-to-ia",
                    transitions: [
                        {
                            storageClass: s3.StorageClass.INFREQUENT_ACCESS,
                            transitionAfter: cdk.Duration.days(90),
                        },
                        {
                            storageClass: s3.StorageClass.GLACIER,
                            transitionAfter: cdk.Duration.days(365),
                        },
                    ],
                },
            ],
        });

        // ====================================================
        // 3. DynamoDB — Audit Logs Table
        // ====================================================
        const auditTable = new dynamodb.Table(this, "AuditLogsTable", {
            partitionKey: { name: "patientId", type: dynamodb.AttributeType.STRING },
            sortKey: { name: "timestamp", type: dynamodb.AttributeType.STRING },
            billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
            encryption: dynamodb.TableEncryption.AWS_MANAGED,
            pointInTimeRecoverySpecification: { pointInTimeRecoveryEnabled: true },
            removalPolicy: cdk.RemovalPolicy.RETAIN,
        });

        auditTable.addGlobalSecondaryIndex({
            indexName: "by-action",
            partitionKey: { name: "action", type: dynamodb.AttributeType.STRING },
            sortKey: { name: "timestamp", type: dynamodb.AttributeType.STRING },
            projectionType: dynamodb.ProjectionType.ALL,
        });

        // ====================================================
        // 4. DynamoDB — Access Grants Table
        // ====================================================
        const accessTable = new dynamodb.Table(this, "AccessGrantsTable", {
            partitionKey: { name: "patientId", type: dynamodb.AttributeType.STRING },
            sortKey: { name: "doctorId", type: dynamodb.AttributeType.STRING },
            billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
            encryption: dynamodb.TableEncryption.AWS_MANAGED,
            removalPolicy: cdk.RemovalPolicy.RETAIN,
            timeToLiveAttribute: "expiresAt",
        });

        // ====================================================
        // 5. DynamoDB — Break-Glass Sessions Table
        // ====================================================
        const sessionTable = new dynamodb.Table(this, "SessionsTable", {
            partitionKey: { name: "sessionId", type: dynamodb.AttributeType.STRING },
            billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
            encryption: dynamodb.TableEncryption.AWS_MANAGED,
            removalPolicy: cdk.RemovalPolicy.RETAIN,
            timeToLiveAttribute: "expiresAt",
        });

        sessionTable.addGlobalSecondaryIndex({
            indexName: "by-patient",
            partitionKey: { name: "patientId", type: dynamodb.AttributeType.STRING },
            sortKey: { name: "startedAt", type: dynamodb.AttributeType.STRING },
            projectionType: dynamodb.ProjectionType.ALL,
        });

        // ====================================================
        // 6. SNS — Notifications Topic
        // ====================================================
        const notificationTopic = new sns.Topic(this, "NotificationsTopic", {
            topicName: "arogyasutra-notifications",
            displayName: "ArogyaSutra Patient Notifications",
        });

        // ====================================================
        // 7. Lambda — Cognito Custom Auth Triggers
        // ====================================================
        const defineAuthFn = new NodejsFunction(this, "DefineAuthChallenge", {
            functionName: "arogyasutra-define-auth",
            runtime: lambda.Runtime.NODEJS_20_X,
            entry: path.join(__dirname, "..", "lambda", "define-auth", "index.ts"),
            handler: "handler",
            timeout: cdk.Duration.seconds(10),
            memorySize: 128,
            bundling: { forceDockerBundling: false },
        });

        const createAuthFn = new NodejsFunction(this, "CreateAuthChallenge", {
            functionName: "arogyasutra-create-auth",
            runtime: lambda.Runtime.NODEJS_20_X,
            entry: path.join(__dirname, "..", "lambda", "create-auth", "index.ts"),
            handler: "handler",
            timeout: cdk.Duration.seconds(10),
            memorySize: 128,
            environment: {
                AWS_SNS_REGION: this.region,
            },
            bundling: { forceDockerBundling: false },
        });

        // Grant SNS publish to create-auth Lambda (for OTP delivery)
        notificationTopic.grantPublish(createAuthFn);
        createAuthFn.addToRolePolicy(
            new iam.PolicyStatement({
                actions: ["sns:Publish"],
                resources: ["*"], // Allow direct SMS publish (not just topic)
            })
        );

        const verifyAuthFn = new NodejsFunction(this, "VerifyAuthChallenge", {
            functionName: "arogyasutra-verify-auth",
            runtime: lambda.Runtime.NODEJS_20_X,
            entry: path.join(__dirname, "..", "lambda", "verify-auth", "index.ts"),
            handler: "handler",
            timeout: cdk.Duration.seconds(10),
            memorySize: 128,
            bundling: { forceDockerBundling: false },
        });

        // ====================================================
        // 8. Cognito — Patient User Pool
        // ====================================================
        const patientPool = new cognito.UserPool(this, "PatientUserPool", {
            userPoolName: "arogyasutra-patients",
            selfSignUpEnabled: false, // Patients are enrolled by admin only
            signInAliases: {
                username: true,
            },
            customAttributes: {
                card_id: new cognito.StringAttribute({
                    minLen: 12,
                    maxLen: 12,
                    mutable: false,
                }),
                dob: new cognito.StringAttribute({ mutable: false }),
            },
            standardAttributes: {
                phoneNumber: { required: true, mutable: true },
                birthdate: { required: true, mutable: false },
                fullname: { required: true, mutable: true },
            },
            passwordPolicy: {
                minLength: 12,
                requireUppercase: true,
                requireDigits: true,
                requireSymbols: true,
                tempPasswordValidity: cdk.Duration.days(1),
            },
            accountRecovery: cognito.AccountRecovery.PHONE_ONLY_WITHOUT_MFA,
            lambdaTriggers: {
                defineAuthChallenge: defineAuthFn,
                createAuthChallenge: createAuthFn,
                verifyAuthChallengeResponse: verifyAuthFn,
            },
            removalPolicy: cdk.RemovalPolicy.RETAIN,
        });

        const patientClient = patientPool.addClient("PatientAppClient", {
            userPoolClientName: "arogyasutra-patient-web",
            authFlows: {
                custom: true,
            },
            preventUserExistenceErrors: true,
            accessTokenValidity: cdk.Duration.hours(1),
            idTokenValidity: cdk.Duration.hours(1),
            refreshTokenValidity: cdk.Duration.days(30),
        });

        // ====================================================
        // 9. Cognito — Doctor User Pool
        // ====================================================
        const doctorPool = new cognito.UserPool(this, "DoctorUserPool", {
            userPoolName: "arogyasutra-doctors",
            selfSignUpEnabled: false, // Doctors are verified & enrolled by admin
            signInAliases: {
                username: true,
                email: true,
            },
            customAttributes: {
                mci_number: new cognito.StringAttribute({
                    minLen: 5,
                    maxLen: 20,
                    mutable: false,
                }),
                institution: new cognito.StringAttribute({ mutable: true }),
                designation: new cognito.StringAttribute({ mutable: true }),
            },
            standardAttributes: {
                email: { required: true, mutable: true },
                fullname: { required: true, mutable: true },
                phoneNumber: { required: true, mutable: true },
            },
            passwordPolicy: {
                minLength: 12,
                requireUppercase: true,
                requireDigits: true,
                requireSymbols: true,
            },
            removalPolicy: cdk.RemovalPolicy.RETAIN,
        });

        const doctorClient = doctorPool.addClient("DoctorAppClient", {
            userPoolClientName: "arogyasutra-doctor-web",
            authFlows: {
                userSrp: true,
                adminUserPassword: true, // Required for server-side ADMIN_USER_PASSWORD_AUTH
            },
            preventUserExistenceErrors: true,
            accessTokenValidity: cdk.Duration.hours(1),
            idTokenValidity: cdk.Duration.hours(1),
            refreshTokenValidity: cdk.Duration.days(7),
        });

        // ====================================================
        // 10. HealthLake — NOT deployed via CDK
        //     HealthLake is only available in:
        //       us-east-1, us-east-2, us-west-2, ap-southeast-2, eu-west-2
        //     Create manually in a supported region, then add
        //     the datastore ID to your .env file.
        // ====================================================

        // ====================================================
        // 11. IAM — App Backend Role (for future Lambda/Amplify)
        // ====================================================
        const appRole = new iam.Role(this, "AppBackendRole", {
            roleName: "arogyasutra-app-backend",
            assumedBy: new iam.CompositePrincipal(
                new iam.ServicePrincipal("lambda.amazonaws.com"),
                new iam.ServicePrincipal("amplify.amazonaws.com")
            ),
        });

        // Grant permissions
        healthBucket.grantReadWrite(appRole);
        masterKey.grantEncryptDecrypt(appRole);
        auditTable.grantReadWriteData(appRole);
        accessTable.grantReadWriteData(appRole);
        sessionTable.grantReadWriteData(appRole);
        notificationTopic.grantPublish(appRole);

        appRole.addToPolicy(
            new iam.PolicyStatement({
                sid: "TextractAccess",
                actions: [
                    "textract:AnalyzeDocument",
                    "textract:DetectDocumentText",
                ],
                resources: ["*"],
            })
        );

        appRole.addToPolicy(
            new iam.PolicyStatement({
                sid: "ComprehendMedicalAccess",
                actions: [
                    "comprehendmedical:DetectEntitiesV2",
                    "comprehendmedical:InferICD10CM",
                    "comprehendmedical:InferRxNorm",
                ],
                resources: ["*"],
            })
        );

        appRole.addToPolicy(
            new iam.PolicyStatement({
                sid: "BedrockAccess",
                actions: [
                    "bedrock:InvokeModel",
                    "bedrock:InvokeModelWithResponseStream",
                ],
                resources: ["*"],
            })
        );

        appRole.addToPolicy(
            new iam.PolicyStatement({
                sid: "HealthLakeAccess",
                actions: [
                    "healthlake:CreateResource",
                    "healthlake:ReadResource",
                    "healthlake:UpdateResource",
                    "healthlake:SearchWithGet",
                    "healthlake:SearchWithPost",
                ],
                resources: ["*"], // HealthLake created manually in us-east-1
            })
        );

        // ====================================================
        // 12. Cognito Identity Pools (for authenticated AWS access)
        // ====================================================
        const identityPool = new cognito.CfnIdentityPool(this, "IdentityPool", {
            identityPoolName: "arogyasutra_identity_pool",
            allowUnauthenticatedIdentities: false,
            cognitoIdentityProviders: [
                {
                    clientId: patientClient.userPoolClientId,
                    providerName: patientPool.userPoolProviderName,
                },
                {
                    clientId: doctorClient.userPoolClientId,
                    providerName: doctorPool.userPoolProviderName,
                },
            ],
        });

        // Authenticated role for identity pool
        const authenticatedRole = new iam.Role(this, "CognitoAuthRole", {
            roleName: "arogyasutra-cognito-authenticated",
            assumedBy: new iam.FederatedPrincipal(
                "cognito-identity.amazonaws.com",
                {
                    StringEquals: {
                        "cognito-identity.amazonaws.com:aud": identityPool.ref,
                    },
                    "ForAnyValue:StringLike": {
                        "cognito-identity.amazonaws.com:amr": "authenticated",
                    },
                },
                "sts:AssumeRoleWithWebIdentity"
            ),
        });

        // Grant the authenticated role access to S3 (scoped to patient prefix)
        healthBucket.grantReadWrite(authenticatedRole, "patients/${cognito-identity.amazonaws.com:sub}/*");
        masterKey.grantEncryptDecrypt(authenticatedRole);

        authenticatedRole.addToPolicy(
            new iam.PolicyStatement({
                sid: "TextractForPatient",
                actions: ["textract:AnalyzeDocument", "textract:DetectDocumentText"],
                resources: ["*"],
            })
        );

        authenticatedRole.addToPolicy(
            new iam.PolicyStatement({
                sid: "ComprehendMedicalForPatient",
                actions: [
                    "comprehendmedical:DetectEntitiesV2",
                    "comprehendmedical:InferICD10CM",
                ],
                resources: ["*"],
            })
        );

        authenticatedRole.addToPolicy(
            new iam.PolicyStatement({
                sid: "BedrockForPatient",
                actions: ["bedrock:InvokeModel"],
                resources: ["*"],
            })
        );

        // Attach role to identity pool
        new cognito.CfnIdentityPoolRoleAttachment(this, "IdentityPoolRoles", {
            identityPoolId: identityPool.ref,
            roles: {
                authenticated: authenticatedRole.roleArn,
            },
        });

        // ====================================================
        // OUTPUTS → Copy these to your .env file
        // ====================================================
        new cdk.CfnOutput(this, "KmsKeyId", {
            value: masterKey.keyId,
            description: "KMS_KEY_ID",
        });

        new cdk.CfnOutput(this, "S3BucketName", {
            value: healthBucket.bucketName,
            description: "NEXT_PUBLIC_S3_BUCKET",
        });

        new cdk.CfnOutput(this, "PatientPoolId", {
            value: patientPool.userPoolId,
            description: "NEXT_PUBLIC_COGNITO_PATIENT_POOL_ID",
        });

        new cdk.CfnOutput(this, "PatientClientId", {
            value: patientClient.userPoolClientId,
            description: "NEXT_PUBLIC_COGNITO_PATIENT_CLIENT_ID",
        });

        new cdk.CfnOutput(this, "DoctorPoolId", {
            value: doctorPool.userPoolId,
            description: "NEXT_PUBLIC_COGNITO_DOCTOR_POOL_ID",
        });

        new cdk.CfnOutput(this, "DoctorClientId", {
            value: doctorClient.userPoolClientId,
            description: "NEXT_PUBLIC_COGNITO_DOCTOR_CLIENT_ID",
        });

        // HealthLake output omitted — create manually in us-east-1
        // and set NEXT_PUBLIC_HEALTHLAKE_DATASTORE_ID in .env

        new cdk.CfnOutput(this, "SnsTopicArn", {
            value: notificationTopic.topicArn,
            description: "SNS_TOPIC_ARN",
        });

        new cdk.CfnOutput(this, "AuditTableName", {
            value: auditTable.tableName,
            description: "DYNAMODB_AUDIT_TABLE",
        });

        new cdk.CfnOutput(this, "AccessTableName", {
            value: accessTable.tableName,
            description: "DYNAMODB_ACCESS_TABLE",
        });

        new cdk.CfnOutput(this, "SessionTableName", {
            value: sessionTable.tableName,
            description: "DYNAMODB_SESSION_TABLE",
        });

        new cdk.CfnOutput(this, "IdentityPoolId", {
            value: identityPool.ref,
            description: "NEXT_PUBLIC_IDENTITY_POOL_ID",
        });

        new cdk.CfnOutput(this, "AppBackendRoleArn", {
            value: appRole.roleArn,
            description: "App backend role ARN",
        });
    }
}
