// ============================================================
// RAG Clinical Assistant Type Definitions
// ============================================================

/** RAG query from patient or doctor */
export interface RAGQuery {
    queryText: string;
    patientId: string;
    queryBy: "PATIENT" | "DOCTOR";
    queryByUserId: string;
    conversationId?: string; // For multi-turn conversations
}

/** RAG response from Bedrock */
export interface RAGResponse {
    answer: string;
    citations: SourceCitation[];
    confidence: number; // 0-100
    modelId: string;
    generatedAt: string;
    conversationId: string;
    disclaimer: string; // Medical disclaimer text
}

/** Source citation linking answer to timeline entries */
export interface SourceCitation {
    entryId: string;
    entryTitle: string;
    documentType: import("./timeline").DocumentTypeTag;
    date: string;
    relevantExcerpt: string;
    relevanceScore: number; // 0-1
}

/** Proactive health insight generated by RAG */
export interface HealthInsight {
    insightId: string;
    patientId: string;
    type: InsightType;
    title: string;
    description: string;
    severity: "info" | "warning" | "alert";
    relatedEntryIds: string[];
    dataPoints: DataPoint[];
    generatedAt: string;
    isRead: boolean;
    isDismissed: boolean;
}

/** Types of proactive insights */
export type InsightType =
    | "trend_rising"      // e.g., "BP rising over 6 months"
    | "trend_declining"   // e.g., "HbA1c improving"
    | "drug_interaction"  // Potential interaction between medications
    | "missed_followup"   // Suggested follow-up based on past visits
    | "abnormal_lab"      // Lab result outside reference range
    | "medication_review" // Long-term medication that needs review
    | "preventive_care";  // Suggested screenings based on age/gender

/** Data point for trend visualization */
export interface DataPoint {
    label: string;
    value: number;
    unit: string;
    date: string;
    entryId: string;
}

/** Chat conversation state */
export interface ChatConversation {
    conversationId: string;
    patientId: string;
    messages: ChatMessage[];
    startedAt: string;
    lastMessageAt: string;
}

/** Single chat message */
export interface ChatMessage {
    messageId: string;
    role: "user" | "assistant";
    content: string;
    citations?: SourceCitation[];
    timestamp: string;
}
